name: Publish Articles to Qiita

on:
  push:
    paths:
      - "Zenn*/publish/*.md"  # フォルダ構成に合わせる

jobs:
  publish_to_qiita:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Qiitaに投稿
        run: |
          for file in Zenn&Qiita/publish/*.md; do
            if grep -q "publish: true" "$file"; then  # publish: true のものだけ投稿
              TITLE=$(grep "^title: " "$file" | cut -d'"' -f2) # titleを取得
              BODY=$(tail -n +5 "$file") # メタデータを除いた本文
              curl -X POST "https://qiita.com/api/v2/items" \
                -H "Authorization: Bearer ${{ secrets.QIITA_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"title\": \"$TITLE\", \"body\": \"$BODY\", \"tags\": [{\"name\": \"技術\"}], \"private\": false}"
            fi
          done
